global:
  listen_address: ':8085'

receivers:

- path: '/grafana'
  snmptrap_configs:
    - addr: 'localhost:162'
      community: 'public'
      option_templates: 
        - 'config/option.tmpl'
  webhook_configs:
    - url: 'http://localhost:8080'
      option_templates: 
        - 'config/json.tmpl'
